<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            [
                'id' => 1,
                'name' => '雾灯框-前右',
                'sku' => 'DXB000221LML',
                'unit_id' => '1',
                'type_id' => '1',
                'weight' => 0,
                'description' => '',
                'picture' => '',
                'note' => '',
            ], [
                'id' => 2,
                'name' => '雾灯框-前左',
                'sku' => 'DXB000231LML',
                'unit_id' => '1',
                'type_id' => '1',
                'weight' => 0,
                'description' => '',
                'picture' => '',
                'note' => '',
            ],[
                'id' => 3,
                'name' => '后视镜片-右',
                'sku' => 'LR017067',
                'unit_id' => '1',
                'type_id' => '1',
                'weight' => 0,
                'description' => '',
                'picture' => '',
                'note' => '',
            ],[
                'id' => 4,
                'name' => '后视镜片-左',
                'sku' => 'LR017070',
                'unit_id' => '1',
                'type_id' => '1',
                'weight' => 0,
                'description' => '',
                'picture' => '',
                'note' => '',
            ],[
                'id' => 5,
                'name' => '备胎绞盘--新款',
                'sku' => 'LR024145',
                'unit_id' => '1',
                'type_id' => '1',
                'weight' => 0,
                'description' => '',
                'picture' => '',
                'note' => '',
            ],[
                'id' => 6,
                'name' => '拖车盖-后PCL',
                'sku' => 'DPO500011PCL',
                'unit_id' => '1',
                'type_id' => '1',
                'weight' => 0,
                'description' => '',
                'picture' => '',
                'note' => '',
            ],[
                'id' => 7,
                'name' => '拖车盖-后132',
                'sku' => 'LR015132',
                'unit_id' => '1',
                'type_id' => '1',
                'weight' => 0,
                'description' => '',
                'picture' => '',
                'note' => '',
            ],[
                'id' => 8,
                'name' => '牌照板',
                'sku' => 'LR019327',
                'unit_id' => '1',
                'type_id' => '1',
                'weight' => 0,
                'description' => '',
                'picture' => '',
                'note' => '',
            ],[
                'id' => 9,
                'name' => '排挡手柄',
                'sku' => 'LR003471',
                'unit_id' => '1',
                'type_id' => '1',
                'weight' => 0,
                'description' => '',
                'picture' => '',
                'note' => '',
            ],[
                'id' => 10,
                'name' => '节温器',
                'sku' => 'LR005765',
                'unit_id' => '1',
                'type_id' => '1',
                'weight' => 0,
                'description' => '',
                'picture' => '',
                'note' => '',
            ],[
                'id' => 11,
                'name' => '雾灯框1',
                'sku' => 'LR015461',
                'unit_id' => '1',
                'type_id' => '1',
                'weight' => 0,
                'description' => '',
                'picture' => '',
                'note' => '',
            ],[
                'id' => 12,
                'name' => '雾灯框2',
                'sku' => 'LR015462',
                'unit_id' => '1',
                'type_id' => '1',
                'weight' => 0,
                'description' => '',
                'picture' => '',
                'note' => '',
            ],[
                'id' => 13,
                'name' => '后视镜框2',
                'sku' => 'LR019962',
                'unit_id' => '1',
                'type_id' => '1',
                'weight' => 0,
                'description' => '',
                'picture' => '',
                'note' => '',
            ],[
                'id' => 14,
                'name' => '后视镜框1',
                'sku' => 'LR019961',
                'unit_id' => '1',
                'type_id' => '1',
                'weight' => 0,
                'description' => '',
                'picture' => '',
                'note' => '',
            ],[
                'id' => 15,
                'name' => '车窗开关',
                'sku' => 'YUD501570PVJ',
                'unit_id' => '1',
                'type_id' => '1',
                'weight' => 0,
                'description' => '',
                'picture' => '',
                'note' => '',
            ],[
                'id' => 16,
                'name' => '雾灯框310',
                'sku' => 'DXB500310LML',
                'unit_id' => '1',
                'type_id' => '1',
                'weight' => 0,
                'description' => '',
                'picture' => '',
                'note' => '',
            ],[
                'id' => 17,
                'name' => '雾灯框330',
                'sku' => 'DXB500330LML',
                'unit_id' => '1',
                'type_id' => '1',
                'weight' => 0,
                'description' => '',
                'picture' => '',
                'note' => '',
            ],[
                'id' => 18,
                'name' => '后视镜片75',
                'sku' => 'LR013775',
                'unit_id' => '1',
                'type_id' => '1',
                'weight' => 0,
                'description' => '',
                'picture' => '',
                'note' => '',
            ],[
                'id' => 19,
                'name' => '后视镜片74',
                'sku' => 'LR013774',
                'unit_id' => '1',
                'type_id' => '1',
                'weight' => 0,
                'description' => '',
                'picture' => '',
                'note' => '',
            ],[
                'id' => 20,
                'name' => '门锁拉线',
                'sku' => 'FQZ000041',
                'unit_id' => '1',
                'type_id' => '1',
                'weight' => 0,
                'description' => '',
                'picture' => '',
                'note' => '',
            ],[
                'id' => 21,
                'name' => '凸轮轴调节器001',
                'sku' => '2710500800',
                'unit_id' => '1',
                'type_id' => '1',
                'weight' => 0,
                'description' => '',
                'picture' => '',
                'note' => '',
            ],[
                'id' => 22,
                'name' => '凸轮轴调节器002',
                'sku' => '2710500900',
                'unit_id' => '1',
                'type_id' => '1',
                'weight' => 0,
                'description' => '',
                'picture' => '',
                'note' => '',
            ],[
                'id' => 23,
                'name' => '凸轮轴调节器003',
                'sku' => '2710503347',
                'unit_id' => '1',
                'type_id' => '1',
                'weight' => 0,
                'description' => '',
                'picture' => '',
                'note' => '',
            ],[
                'id' => 24,
                'name' => '凸轮轴调节器004',
                'sku' => '2710503447',
                'unit_id' => '1',
                'type_id' => '1',
                'weight' => 0,
                'description' => '',
                'picture' => '',
                'note' => '',
            ],
        ]);
    }
}
